%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                 %
%     Generates data for CNN      %
%                                 %
% leonel.m.carvalho@inesctec.pt   %
%                                 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all;
close all;
clc;

warning('off','all');

addpath(genpath(pwd));
define_constants;


%% Import data 

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Leonel Carvalho\Desktop\Daniel Schlickmann\matpower7.1\carga_anual.csv
%
% Auto-generated by MATLAB on 17-Aug-2022 11:33:22

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
carga_anual = readtable("C:\Users\Leonel Carvalho\Desktop\Daniel Schlickmann\matpower7.1\carga_anual.csv", opts);

%% Convert to output type
carga_anual = table2array(carga_anual);

carga_anual_138 = carga_anual(:,1);
carga_anual_230 = carga_anual(:,2);

%% Clear temporary variables
clear opts


%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Leonel Carvalho\Desktop\Daniel Schlickmann\matpower7.1\eolica_anual.csv
%
% Auto-generated by MATLAB on 24-Jul-2022 12:11:38

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
eolica_anual = readtable("matpower7.1\eolica_anual.csv", opts);

%% Convert to output type
eolica_anual = table2array(eolica_anual);

eolica_anual_138 = eolica_anual(:,1);
eolica_anual_230 = eolica_anual(:,2);

%% Clear temporary variables
clear opts

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Leonel Carvalho\Desktop\Daniel Schlickmann\matpower7.1\solar_anual.csv
%
% Auto-generated by MATLAB on 17-Aug-2022 11:35:46

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
solar_anual = readtable("C:\Users\Leonel Carvalho\Desktop\Daniel Schlickmann\matpower7.1\solar_anual.csv", opts);

%% Convert to output type
solar_anual = table2array(solar_anual);

solar_anual_138 = solar_anual(:,1);
solar_anual_230 = solar_anual(:,2);

%% Clear temporary variables
clear opts

%% AC Load Flow %% 

% Define case
net_ori = loadcase('case24_ieee_rts_mod.m');

%% Modify case
net_ori.gen(34,GEN_BUS) = 8; % parque eólico 138
net_ori.gen(35,GEN_BUS) = 5; % parque solar 138
net_ori.gen(36,GEN_BUS) = 20; % parque eólico 230
net_ori.gen(37,GEN_BUS) = 17; % parque solar 230

net_ori.gen(34,PMAX) = 1000; % parque eólico 138
net_ori.gen(35,PMAX) = 1500; % parque solar 138
net_ori.gen(36,PMAX) = 375; % parque eólico 230
net_ori.gen(37,PMAX) = 250; % parque solar 230

net_ori.gen(34,QMAX) = net_ori.gen(34,PMAX) * 0.8; % parque eólico 138
net_ori.gen(35,QMAX) = net_ori.gen(35,PMAX) * 0.8; % parque solar 138
net_ori.gen(36,QMAX) = net_ori.gen(36,PMAX) * 0.8; % parque eólico 230
net_ori.gen(37,QMAX) = net_ori.gen(37,PMAX) * 0.8; % parque solar 230 

net_ori.gen(34,QMIN) = -net_ori.gen(34,QMAX); % parque eólico 138
net_ori.gen(35,QMIN) = -net_ori.gen(35,QMAX); % parque solar 138
net_ori.gen(36,QMIN) = -net_ori.gen(36,QMAX); % parque eólico 230
net_ori.gen(37,QMIN) = -net_ori.gen(37,QMAX); % parque solar 230  

%% Run case
mpopt = mpoption('model','AC', 'out.all', 0);
net_pf = runopf(net_ori,mpopt);


%% Run case for the whole year
n_tt= 8760; %% number of hours in the year

% - voltage mangitude at bus 11
% - voltage mangitude at bus 12
% - voltage mangitude at bus 24
% - active power flow at bus 11
% - active power flow at bus 12
% - active power flow at bus 24
% - reactive power flow at bus 11
% - reactive power flow at bus 12
% - reactive power flow at bus 24
output_data_nn = zeros( n_tt, 9 );

% - total load in 138 kV system
% - total solar power in 138 kV system
% - total wind power in 138 kV system
% - total load in 230 kV system
% - total solar power in 230 kV system
% - total wind power in 230 kV system
% - status generators in 138 kV system
% - status transmission lines in 138 kV system
% - status generators in 230 kV system
% - status transmission lines in 230 kV system

index_gen_138 = 1:1:11;
index_gen_138 = [index_gen_138, [34,35]];
index_gen_230 = 12:1:33;
index_gen_230 = [index_gen_230, [36,37]];

index_trans_line_138 = 1:1:17;
index_trans_line_230 = 18:1:38;

input_data_nn = zeros( n_tt, 6 + length(index_gen_138) + length(index_trans_line_138) + length(index_gen_230) + length(index_trans_line_230) );

for tt = 1 : n_tt
    % load network
    net_pf = net_ori;

    % update load
    for i = 1 : length(net_pf.bus(:,PD))
        if i <= 10
            net_pf.bus(i,PD) = net_pf.bus(i,PD) .* carga_anual_138( tt, 1 );
            net_pf.bus(i,QD) = net_pf.bus(i,QD) .* carga_anual_138( tt, 1 );
        else
            net_pf.bus(i,PD) = net_pf.bus(i,PD) .* carga_anual_230( tt, 1 );
            net_pf.bus(i,QD) = net_pf.bus(i,QD) .* carga_anual_230( tt, 1 );
        end
    end
    
    % update generation
    net_pf.gen(34,PMAX) = net_pf.gen(34,PMAX) * eolica_anual_138(tt, 1); % parque eólico 138
    net_pf.gen(35,PMAX) = net_pf.gen(35,PMAX) * solar_anual_138(tt, 1); % parque solar 138
    net_pf.gen(36,PMAX) = net_pf.gen(36,PMAX) * eolica_anual_230(tt, 1); % parque eólico 230
    net_pf.gen(37,PMAX) = net_pf.gen(37,PMAX) * solar_anual_230(tt, 1); % parque solar 230

    % runs opf
    net_pf = runopf(net_pf,mpopt);
    
    % saves data
    output_data_nn( tt, 1 ) = net_pf.bus(11, VM);
    output_data_nn( tt, 2 ) = net_pf.bus(12, VM);
    output_data_nn( tt, 3 ) = net_pf.bus(24, VM);
    output_data_nn( tt, 4 ) = net_pf.branch(14, PT);
    output_data_nn( tt, 5 ) = net_pf.branch(17, PT);
    output_data_nn( tt, 6 ) = net_pf.branch(7, PT);
    output_data_nn( tt, 7 ) = net_pf.branch(17, QT);
    output_data_nn( tt, 8 ) = net_pf.branch(24, QT);
    output_data_nn( tt, 9 ) = net_pf.branch(7, QT);

    input_data_nn( tt, 1 ) = sum( net_pf.bus(1:10, PD) );
    input_data_nn( tt, 2 ) = net_pf.gen(35,PG);
    input_data_nn( tt, 3 ) = net_pf.gen(34,PG);  
    input_data_nn( tt, 4 ) = sum( net_pf.bus(11:end, PD) );
    input_data_nn( tt, 5 ) = net_pf.gen(37,PG);
    input_data_nn( tt, 6 ) = net_pf.gen(36,PG);    

    input_data_nn( tt, (6+1):(6+length(index_gen_138)) ) = net_pf.gen(index_gen_138,GEN_STATUS)';
    input_data_nn( tt, (6+length(index_gen_138)+1):(6+length(index_gen_138)+length(index_trans_line_138)) ) = net_pf.branch(index_trans_line_138,BR_STATUS)';

    input_data_nn( tt, (6+length(index_gen_138)+length(index_trans_line_138)+1):(6+length(index_gen_138)+length(index_trans_line_138)+length(index_gen_230)) ) = net_pf.gen(index_gen_230,GEN_STATUS)';
    input_data_nn( tt, (6+length(index_gen_138)+length(index_trans_line_138)+length(index_gen_230)+1):end ) = net_pf.branch(index_trans_line_230,BR_STATUS)';
end

% plot figure
figure();
plot(output_data_nn(:,4));
hold on
plot(output_data_nn(:,5));
plot(output_data_nn(:,6));
grid on;
grid minor;
ylabel('MW');


% save data
writematrix(input_data_nn,'input_data_nn.csv','Delimiter',';');
writematrix(output_data_nn,'output_data_nn.csv','Delimiter',';');
